= Cheatsheets

[[AuthenticationOptions]]
== AuthenticationOptions

++++
 Authentication options.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[enabled]]`enabled`|`Boolean`|
+++
Set whether authentication is enabled. Defaults to <code>false</code>.
+++
|[[secret]]`secret`|`String`|
+++
Set the secret used for authentication.
+++
|[[username]]`username`|`String`|
+++
Set the identifier used for authentication.
+++
|===

[[BatchingReporterOptions]]
== BatchingReporterOptions

++++
 Common options for reporters sending metrics in batches.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[batchDelay]]`batchDelay`|`Number (int)`|
+++
Set the maximum delay between two consecutive batches (in seconds). To reduce the number of HTTP exchanges, metric
 data is sent by the reporter in batches. A batch is sent as soon as the number of metrics collected reaches
 the configured <code>batchSize</code>, or after the <code>batchDelay</code> expires. Defaults to <code>1</code> second.
+++
|[[batchSize]]`batchSize`|`Number (int)`|
+++
Set the maximum number of metrics in a batch. To reduce the number of HTTP exchanges, metric data is sent by the
 reporter in batches. A batch is sent as soon as the number of metrics collected reaches the configured
 <code>batchSize</code>, or after the <code>batchDelay</code> expires. Defaults to <code>50</code>.
+++
|[[disabledMetricsCategories]]`disabledMetricsCategories`|`Array of link:enums.html#MetricsCategory[MetricsCategory]`|
+++
Sets metrics types that are disabled.
+++
|[[enabled]]`enabled`|`Boolean`|
+++
Set whether metrics will be enabled on the Vert.x instance. Metrics are not enabled by default.
+++
|[[metricsBridgeAddress]]`metricsBridgeAddress`|`String`|
+++
Sets the metric bridge address on which the application is sending the custom metrics. Application can send
 metrics to this event bus address. The message is a JSON object specifying at least the <code>id</code> and
 <code>value</code> fields.
 <p/>
 Don't forget to also enable the bridge with <code>metricsBridgeEnabled</code>.
+++
|[[metricsBridgeEnabled]]`metricsBridgeEnabled`|`Boolean`|
+++
Sets whether or not the metrics bridge should be enabled. The metrics bridge is disabled by default.
+++
|[[prefix]]`prefix`|`String`|
+++
Set the metric name prefix. Metric names are not prefixed by default. Prefixing metric names is required to
 distinguish data sent by different Vert.x instances.
+++
|[[schedule]]`schedule`|`Number (int)`|
+++
Set the metric collection interval (in seconds). Defaults to <code>1</code>.
+++
|===

[[MetricsOptionsBase]]
== MetricsOptionsBase

++++
 Base options for metrics reporting.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[disabledMetricsCategories]]`disabledMetricsCategories`|`Array of link:enums.html#MetricsCategory[MetricsCategory]`|
+++
Sets metrics types that are disabled.
+++
|[[enabled]]`enabled`|`Boolean`|
+++
Set whether metrics will be enabled on the Vert.x instance. Metrics are not enabled by default.
+++
|===

[[VertxInfluxDbOptions]]
== VertxInfluxDbOptions

++++
 Vert.x InfluxDb monitoring configuration.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[authenticationOptions]]`authenticationOptions`|`link:dataobjects.html#AuthenticationOptions[AuthenticationOptions]`|
+++
Set the options for authentication.
+++
|[[batchDelay]]`batchDelay`|`Number (int)`|
+++
Set the maximum delay between two consecutive batches (in seconds). To reduce the number of HTTP exchanges, metric
 data is sent by the reporter in batches. A batch is sent as soon as the number of metrics collected reaches
 the configured <code>batchSize</code>, or after the <code>batchDelay</code> expires. Defaults to <code>1</code> second.
+++
|[[batchSize]]`batchSize`|`Number (int)`|
+++
Set the maximum number of metrics in a batch. To reduce the number of HTTP exchanges, metric data is sent by the
 reporter in batches. A batch is sent as soon as the number of metrics collected reaches the configured
 <code>batchSize</code>, or after the <code>batchDelay</code> expires. Defaults to <code>50</code>.
+++
|[[database]]`database`|`String`|
+++
Set the InfluxDb database. Defaults to <code>default</code>.
+++
|[[disabledMetricsCategories]]`disabledMetricsCategories`|`Array of link:enums.html#MetricsCategory[MetricsCategory]`|
+++
Sets metrics types that are disabled.
+++
|[[enabled]]`enabled`|`Boolean`|
+++
Set whether metrics will be enabled on the Vert.x instance. Metrics are not enabled by default.
+++
|[[gzipEnabled]]`gzipEnabled`|`Boolean`|-
|[[host]]`host`|`String`|
+++
Set the InfluxDb Metrics service host. Defaults to <code>localhost</code>.
+++
|[[httpHeaders]]`httpHeaders`|`Json object`|
+++
Set specific headers to include in HTTP requests.
+++
|[[httpOptions]]`httpOptions`|`link:dataobjects.html#HttpClientOptions[HttpClientOptions]`|
+++
Set the configuration of the InfluxDb Metrics HTTP client.
+++
|[[measurement]]`measurement`|`String`|
+++
Set the InfluxDb measurement. Defaults to <code>vert.x</code>.
+++
|[[metricsBridgeAddress]]`metricsBridgeAddress`|`String`|
+++
Sets the metric bridge address on which the application is sending the custom metrics. Application can send
 metrics to this event bus address. The message is a JSON object specifying at least the <code>id</code> and
 <code>value</code> fields.
 <p/>
 Don't forget to also enable the bridge with <code>metricsBridgeEnabled</code>.
+++
|[[metricsBridgeEnabled]]`metricsBridgeEnabled`|`Boolean`|
+++
Sets whether or not the metrics bridge should be enabled. The metrics bridge is disabled by default.
+++
|[[metricsServiceUri]]`metricsServiceUri`|`String`|
+++
Set the InfluxDb Metrics service URI. Defaults to <code>/InfluxDb/metrics</code>. This can be useful if you host the
 InfluxDb server behind a proxy and manipulate the default service URI.
+++
|[[port]]`port`|`Number (int)`|
+++
Set the InfluxDb Metrics service port.  Defaults to <code>8080</code>.
+++
|[[prefix]]`prefix`|`String`|
+++
Set the metric name prefix. Metric names are not prefixed by default. Prefixing metric names is required to
 distinguish data sent by different Vert.x instances.
+++
|[[schedule]]`schedule`|`Number (int)`|
+++
Set the metric collection interval (in seconds). Defaults to <code>1</code>.
+++
|===

[[VertxPrometheusOptions]]
== VertxPrometheusOptions

++++
 Vert.x Prometheus monitoring configuration.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[disabledMetricsCategories]]`disabledMetricsCategories`|`Array of link:enums.html#MetricsCategory[MetricsCategory]`|
+++
Sets metrics types that are disabled.
+++
|[[embeddedServerEndpoint]]`embeddedServerEndpoint`|`String`|
+++
Set metrics endpoint. Use conjointly with the embedded server options.
+++
|[[embeddedServerOptions]]`embeddedServerOptions`|`link:dataobjects.html#HttpServerOptions[HttpServerOptions]`|
+++
An embedded server will start to expose metrics with Prometheus format
+++
|[[enableRemoteLabelForClients]]`enableRemoteLabelForClients`|`Boolean`|
+++
Set false to prevent generation of a label named "remote" on client-related metrics, used to group data points per remote.
 This is relevant when the application makes client connections to a large number of different clients,
 in order to reduce the number of related prometheus metrics created.<br/>
 This option is set to <i>true</i> by default.
+++
|[[enableRemoteLabelForServers]]`enableRemoteLabelForServers`|`Boolean`|
+++
Set true to allow generation of a label named "remote" on server-related metrics, used to group data points per remote.
 This is relevant when the number of clients connecting to the application servers is small and under control,
 in order to reduce the number of related prometheus metrics created.<br/>
 This option is set to <i>false</i> by default.
+++
|[[enabled]]`enabled`|`Boolean`|
+++
Set whether metrics will be enabled on the Vert.x instance. Metrics are not enabled by default.
+++
|[[registryName]]`registryName`|`String`|
+++
Set a name for the prometheus registry, so that a new registry will be created and associated with this name.
 To retrieve this registry later, call <code>PrometheusRegistries.get(String)</code>
 Doing so allows to provide application-defined metrics to the same registry.
 If <code>registryName</code> is not provided (or null), Prometheus default registry will be used.
+++
|===

