= Cheatsheets

[[VertxPrometheusOptions]]
== VertxPrometheusOptions

++++
 Vert.x Prometheus monitoring configuration.
 If no embedded server is used, you can bind an existing link with <br/>
 Ex:<br/>
 <code>myRouter.route("/metrics").handler(PrometheusVertxMetrics.createMetricsHandler());</code>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[disabledMetricsCategories]]`disabledMetricsCategories`|`Array of link:enums.html#MetricsCategory[MetricsCategory]`|-
|[[embeddedServerEndpoint]]`embeddedServerEndpoint`|`String`|
+++
Set metrics endpoint. Use conjointly with link
+++
|[[embeddedServerOptions]]`embeddedServerOptions`|`link:dataobjects.html#HttpServerOptions[HttpServerOptions]`|
+++
An embedded server will start to expose metrics with Prometheus format
+++
|[[enableRemoteLabelForClients]]`enableRemoteLabelForClients`|`Boolean`|
+++
Set false to prevent generation of a label named "remote" on client-related metrics, used to group data points per remote.
 This is relevant when the application makes client connections to a large number of different clients,
 in order to reduce the number of related prometheus metrics created.<br/>
 This option is set to <i>true</i> by default.
+++
|[[enableRemoteLabelForServers]]`enableRemoteLabelForServers`|`Boolean`|
+++
Set true to allow generation of a label named "remote" on server-related metrics, used to group data points per remote.
 This is relevant when the number of clients connecting to the application servers is small and under control,
 in order to reduce the number of related prometheus metrics created.<br/>
 This option is set to <i>false</i> by default.
+++
|[[enabled]]`enabled`|`Boolean`|
+++
Set whether metrics will be enabled on the Vert.x instance. Metrics are not enabled by default.
+++
|[[metricsBridgeAddress]]`metricsBridgeAddress`|`String`|-
|[[metricsBridgeEnabled]]`metricsBridgeEnabled`|`Boolean`|-
|[[registryName]]`registryName`|`String`|
+++
Set a name for the prometheus registry, so that a new registry will be created and associated with this name.
 To retrieve this registry later, call link
 Doing so allows to provide application-defined metrics to the same registry.
 If <code>registryName</code> is not provided (or null), Prometheus default registry will be used.
+++
|===

