= Vert.x Monitoring for Prometheus
:source-language: java

image::https://vertx.ci.cloudbees.com/buildStatus/icon?job=vert.x3-monitoring[link=https://vertx.ci.cloudbees.com/job/vert.x3-monitoring/]

Vert.x-Prometheus-Metrics contains metrics collection and reporting for https://prometheus.io/[Prometheus].

The http://vertx.io/docs/vertx-core/java/index.html#_metrics_spi[Vert.x Metrics SPI] allows implementers to
capture events from Vert.x in order to gather metrics.

This project is an implementation of the Vert.x Metrics SPI for Prometheus: metrics built from Vert.x events will be exposed
on an HTTP endpoint using Prometheus format.

Please see the in-source Asciidoc documentation or the main documentation on the web-site for a full description
of this component:

* link:http://vertx.io/docs/vertx-monitoring-prometheus/[web-site docs]
* link:src/main/asciidoc[in-source docs]

== Quick setup

To use the Prometheus reporter, you need first to get a running Prometheus instance.
See link:https://prometheus.io/docs/prometheus/latest/installation/[Prometheus installation].

Configure Prometheus to scrape your Vert.x server. Example in `prometheus.yml`:

```yml
scrape_configs:
  - job_name: 'myapp'
    static_configs:
      - targets: ['localhost:9091']
```

It will match a configuration like:

```java
    Vertx vertx = Vertx.vertx(new VertxOptions().setMetricsOptions(
      new VertxPrometheusOptions().setEnabled(true)
        .embedServer(new VertxPrometheusServerOptions().port(9091))));
```
